// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadNginxmon returns the embedded CollectionSpec for nginxmon.
func loadNginxmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NginxmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nginxmon: %w", err)
	}

	return spec, err
}

// loadNginxmonObjects loads nginxmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nginxmonObjects
//	*nginxmonPrograms
//	*nginxmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNginxmonObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNginxmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nginxmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nginxmonSpecs struct {
	nginxmonProgramSpecs
	nginxmonMapSpecs
	nginxmonVariableSpecs
}

// nginxmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nginxmonProgramSpecs struct {
	HandleNgxFinalize *ebpf.ProgramSpec `ebpf:"handle_ngx_finalize"`
}

// nginxmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nginxmonMapSpecs struct {
	NginxConfigMap *ebpf.MapSpec `ebpf:"nginx_config_map"`
	NginxEvents    *ebpf.MapSpec `ebpf:"nginx_events"`
}

// nginxmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nginxmonVariableSpecs struct {
}

// nginxmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNginxmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type nginxmonObjects struct {
	nginxmonPrograms
	nginxmonMaps
	nginxmonVariables
}

func (o *nginxmonObjects) Close() error {
	return _NginxmonClose(
		&o.nginxmonPrograms,
		&o.nginxmonMaps,
	)
}

// nginxmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNginxmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type nginxmonMaps struct {
	NginxConfigMap *ebpf.Map `ebpf:"nginx_config_map"`
	NginxEvents    *ebpf.Map `ebpf:"nginx_events"`
}

func (m *nginxmonMaps) Close() error {
	return _NginxmonClose(
		m.NginxConfigMap,
		m.NginxEvents,
	)
}

// nginxmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNginxmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type nginxmonVariables struct {
}

// nginxmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNginxmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type nginxmonPrograms struct {
	HandleNgxFinalize *ebpf.Program `ebpf:"handle_ngx_finalize"`
}

func (p *nginxmonPrograms) Close() error {
	return _NginxmonClose(
		p.HandleNgxFinalize,
	)
}

func _NginxmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nginxmon_x86_bpfel.o
var _NginxmonBytes []byte
